In [1]:
# 라이브러리 불러오기
import pandas as pd

# 중복 데이터를 갖는 데이터프레임 만들기
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2]})
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [2]:
# 데이터프레임 전체 행 데이터 중에서 중복값 찾기 (기본값, keep='first')
df_dup_first = df.duplicated()
df_dup_first

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [3]:
# 데이터프레임 전체 행 데이터 중에서 중복값 찾기 (keep='last')
df_dup_last = df.duplicated(keep='last')
df_dup_last

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [4]:
# 데이터프레임 전체 행 데이터 중에서 중복값 찾기 (keep=False)
df_dup_false = df.duplicated(keep=False)
df_dup_false

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [5]:
# 데이터프레임의 특정 열 데이터에서 중복값 찾기
col_dup = df['c2'].duplicated()
col_dup

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [6]:
# 데이터프레임의 특정 열 데이터에서 중복값 찾기
col_dup2 = df.duplicated(subset=['c2'])
col_dup2

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [7]:
# 라이브러리 불러오기
import pandas as pd

# 중복 데이터를 갖는 데이터프레임 만들기
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2]})
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [8]:
# 데이터프레임에서 중복 행을 제거 (기본값, keep='first')
df2 = df.drop_duplicates()
df2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [9]:
# 데이터프레임에서 중복 행을 제거 (keep='last')
df3 = df.drop_duplicates(keep='last')
df3

  c1  c2  c3
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [10]:
# 데이터프레임에서 중복 행을 제거 (keep=False)
df4 = df.drop_duplicates(keep=False)
df4

  c1  c2  c3
2  b   1   2
3  a   2   2
4  b   2   2

In [11]:
# c2, c3열을 기준으로 중복 행을 제거
df5 = df.drop_duplicates(subset=['c2', 'c3'])
df5

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [12]:
# c2, c3열을 기준으로 중복 행을 제거 (중복 데이터를 모두 제거)
df6 = df.drop_duplicates(subset=['c2', 'c3'], keep=False)
df6

  c1  c2  c3
2  b   1   2