In [1]:
import pandas as pd

# HTML 파일 경로 or 웹 페이지 주소를 url 변수에 저장
url = './data/sample.html'

# HTML 웹페이지의 표(table)를 가져와서 데이터프레임으로 변환 
tables = pd.read_html(url)   

# 표(table)의 개수 확인
print(len(tables))

2

In [2]:
# tables 리스트의 원소를 iteration하면서 각각 화면 출력
for i in range(len(tables)):
    print(f"tables[{i}]")
    print(tables[i])
    print('\n')

tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9


tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [3]:
# 파이썬 패키지 정보가 들어 있는 두 번째 데이터프레임을 선택하여 df 변수에 저장
df = tables[1] 
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [4]:
# 'name' 열을 인덱스로 지정
df = df.set_index(['name'])
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

In [5]:
# 라이브러리 불러오기
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [10]:
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds"

headers = {
    "User-Agent": "PythonStudyProject/1.0 (contact: your-email@example.com)"
}

resp = requests.get(url, headers=headers)

print("resp:", resp)
print("status_code:", resp.status_code)

soup = BeautifulSoup(resp.text, "lxml")

rows = soup.select("div > ul > li")

etfs = {}

for i in range(len(rows)):
    etfs[i] = rows[i].text.strip()

print("rows 개수:", len(rows))
print("=" * 100)

for i in range(50, 55):
    print(i, ":", etfs[i])

resp: <Response [200]>
status_code: 200
rows 개수: 452
====================================================================================================
50 : Schwab US Broad Market ETF (NYSE Arca: SCHB)
51 : Schwab Fundamental U.S. Broad Market Index ETF (NYSE Arca: FNDB)
52 : Vanguard Total World Stock (NYSE Arca: VT), tracks the FTSE All-World Index
53 : Vanguard Total Stock Market (NYSE Arca: VTI), tracks the MSCI US Broad Market Index
54 : Vanguard Total International Stock (NYSE Arca: VXUS), tracks the MSCI All Country World ex-USA Investable Market Index

In [11]:
etfs = {}
for row in rows:
    
    try:
        etf_name = re.findall("(.+?)\s\(", row.text)
        etf_market = re.findall("\((.+?):", row.text)
        etf_ticker = re.findall(":\s(.+)\)", row.text)
        
        if (len(etf_ticker) > 0) & (len(etf_market) > 0) & (len(etf_name) > 0):
            etfs[etf_ticker[0]] = [etf_market[0], etf_name[0]]

    except AttributeError as err:
        pass    

# etfs 딕셔너리 출력
print(etfs)

{'ITOT': ['NYSE\xa0Arca', 'iShares Core S&P Total US Stock Mkt'], 'ACWI': ['Nasdaq', 'iShares MSCI ACWI Index'], 'IWV': ['NYSE\xa0Arca', 'iShares Russell 3000 Index'], 'SCHB': ['NYSE\xa0Arca', 'Schwab US Broad Market ETF'], 'FNDB': ['NYSE\xa0Arca', 'Schwab Fundamental U.S. Broad Market Index ETF'], 'VT': ['NYSE\xa0Arca', 'Vanguard Total World Stock'], 'VTI': ['NYSE\xa0Arca', 'Vanguard Total Stock Market'], 'VXUS': ['NYSE\xa0Arca', 'Vanguard Total International Stock'], 'VTHR': ['NYSE\xa0Arca', 'Vanguard Russell 3000']}

<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:6: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:7: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:6: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:7: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\Win11Pro\AppData\Local\Temp\ipykernel_17808\1232222225.py:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  etf_name = re.findall("(.+?)\s\(", row.text)
C:\Users\Win11Pro\AppData\Local\Temp\ipykernel_17808\1232222225.py:6: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  etf_market = re.findall("\((.+?):", row.text)
C:\Users\Win11Pro\AppData\Local\Temp\ipykernel_17808\1232222225.py:7: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  etf_ticker = re.findall(":\s(.+)\)", row.text)

In [12]:
# etfs 딕셔너리를 데이터프레임으로 변환
df = pd.DataFrame(etfs)
df

,ITOT,ACWI,IWV,SCHB,FNDB,VT,VTI,VXUS,VTHR
0,NYSE Arca,Nasdaq,NYSE Arca,NYSE Arca,NYSE Arca,NYSE Arca,NYSE Arca,NYSE Arca,NYSE Arca
1,iShares Core S&P Total US Stock Mkt,iShares MSCI ACWI Index,iShares Russell 3000 Index,Schwab US Broad Market ETF,Schwab Fundamental U.S. Broad Market Index ETF,Vanguard Total World Stock,Vanguard Total Stock Market,Vanguard Total International Stock,Vanguard Russell 3000