In [17]:
# 라이브러리 가져오기
import requests
import pandas as pd

In [18]:
my_key = "2642b6273880ab07de2dd637b5b3450f"

In [19]:
# Kakao Map API 통해 위도, 경도 데이터 가져오는 함수를 정의
def get_geocoding(place):
    url = f"https://dapi.kakao.com/v2/local/search/address.json?query={place}"
    headers = {"Authorization": f"KakaoAK {my_key}"}
    response = requests.get(url, headers=headers)
    result = response.json()
    return result["documents"][0]["y"], result["documents"][0]["x"]

In [20]:
lat = []  #위도
lng = []  #경도

# 장소(주소) 리스트
places = ["서울특별시 종로구 세종대로 175", 
          "서울특별시 서초구 서초동 700", 
          "부산광역시 해운대구 해운대해변로 264"]

i=0
for place in places:   
    i = i + 1
    try:
        print(i, place)
        # get_geocoding 함수의 리턴값 호출하여 geo_location 변수에 저장
        place_lat, place_lon = get_geocoding(place)
        lat.append(place_lat)
        lng.append(place_lon)
        
    except:
        lat.append('')
        lng.append('')

# 데이터프레임으로 변환하기
df = pd.DataFrame({'위도':lat, '경도':lng}, index=places)

df

1 서울특별시 종로구 세종대로 175
2 서울특별시 서초구 서초동 700
3 부산광역시 해운대구 해운대해변로 264

                                     위도                경도
서울특별시 종로구 세종대로 175     37.5718478584908  126.976168275947
서울특별시 서초구 서초동 700      37.4810862955299  127.015245160054
부산광역시 해운대구 해운대해변로 264  35.1591069824231  129.160283786856

In [ ]:
import requests
import pandas as pd

my_key = ''

def get_financials(stockCode, indicatorName, apiKey, consolidated=True, ttm=True):
    
    if consolidated:
        if ttm:
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByTTM?&indicatorName={indicatorName}&stockCode={stockCode}"            
        else:
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByCUR?&indicatorName={indicatorName}&stockCode={stockCode}"       
    else:
        if ttm:
            url = f"https://api.dapada.io/company/getSeparatedFinancialDataByTTM?indicatorName={indicatorName}&stockCode={stockCode}"            
        else:
            url = f"https://api.dapada.io/company/getSeparatedFinancialDataByCUR?indicatorName={indicatorName}&stockCode={stockCode}"       
           
    headers = {"Authorization": f"{apiKey}"}
    response = requests.get(url, headers=headers)
    result = response.json()
    return pd.DataFrame(result)

In [50]:
# 삼성전자(005930)의 연결 재무제표 (분기 기준)에서 "매출액" 항목의 데이터 수집
df_cur_consolidated = get_financials(stockCode='005930', 
                                     indicatorName='매출액', 
                                     apiKey=my_key, 
                                     consolidated=True, 
                                     ttm=False)

df_cur_consolidated

            value  quarter
0  67404652000000  2023-Q3
1  60005533000000  2023-Q2
2  63745371000000  2023-Q1
3  70464575000000  2022-Q4
4  76781680000000  2022-Q3
5  77203607000000  2022-Q2
6  77781498000000  2022-Q1

In [ ]:
# data.go.kr
## 국토교통부 아파트 매매 실거래가 자료
import requests 
import xml.etree.ElementTree as ET

SERVICE_KEY = ''
url = "https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade"

def fetch_apt_trade(serviceKey, LAWD_CD, DEAL_YMD):
    params = {
        "serviceKey" : serviceKey,
        "LAWD_CD" : LAWD_CD,
        "DEAL_YMD" : DEAL_YMD
    }

    response = requests.get(url, params = params)
    print(response.content)

fetch_apt_trade(SERVICE_KEY, LAWD_CD = '11110', DEAL_YMD = '202604')

b'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong> </aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(4\xeb\x8b\xa8\xec\xa7\x80)</aptNm><buildYear>2017</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>139,000</dealAmount><dealDay>29</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>19</floor><jibun>126</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x8f\x84\xec\x8b\x9c\xea\xb7\xb8\xeb\xa6\xb0\xeb\xb9\x8c\xeb\x9d\xbc</aptNm><buildYear>1997</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>32,000</dealAmount><dealDay>28</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>44.4</excluUseAr><floor>6</floor><jibun>181-121</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xea\xb4\x91\xed\x99\x94\xeb\xac\xb8\xec\x8a\xa4\xed\x8e\x98\xec\x9d\xb4\xec\x8a\xa4\xeb\xb3\xb8(101\xeb\x8f\x99~105\xeb\x8f\x99)</aptNm><buildYear>2008</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>258,000</dealAmount><dealDay>14</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>146.92</excluUseAr><floor>14</floor><jibun>9</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\x82\xac\xec\xa7\x81\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\x95\x84\xeb\x82\xa81</aptNm><buildYear>1995</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>119,500</dealAmount><dealDay>24</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.9</excluUseAr><floor>8</floor><jibun>4</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xeb\xaa\x85\xeb\xa5\x9c2\xea\xb0\x80</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x8f\x99\xec\x95\x84</aptNm><buildYear>1995</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>83,000</dealAmount><dealDay>19</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.28</excluUseAr><floor>7</floor><jibun>101</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8</aptNm><buildYear>1966</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>35,000</dealAmount><dealDay>29</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>28.8</excluUseAr><floor>1</floor><jibun>328-17</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xed\x98\x84\xeb\x8c\x80\xeb\x9c\xa8\xeb\xa0\x88\xeb\xb9\x84\xec\x95\x99</aptNm><buildYear>2003</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>48,800</dealAmount><dealDay>28</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>48.54</excluUseAr><floor>5</floor><jibun>55</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\x9d\xb5\xec\x84\xa0\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa92</aptNm><buildYear>1993</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>74,000</dealAmount><dealDay>25</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>54.7</excluUseAr><floor>4</floor><jibun>703</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\x95\x84\xeb\x82\xa81</aptNm><buildYear>1995</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>112,000</dealAmount><dealDay>19</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.9</excluUseAr><floor>4</floor><jibun>4</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xeb\xaa\x85\xeb\xa5\x9c2\xea\xb0\x80</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa92</aptNm><buildYear>1993</buildYear><buyerGbn>\xea\xb0\x9c\xec\x9d\xb8</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>69,800</dealAmount><dealDay>29</dealDay><dealMonth>4</dealMonth><dealYear>2026</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac, \xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>54.7</excluUseAr><floor>1</floor><jibun>703</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>\xea\xb0\x9c\xec\x9d\xb8</slerGbn><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>85</totalCount></body></response>'

In [ ]:
url = 'https://apis.data.go.kr/B552696/countrygrade/credit-grade'
SERVICE_KEY = ''

def country_credit_rating(page_no = 1, num_of_row = 100):

    params = {
    'serviceKey': SERVICE_KEY,
    'pageNo': page_no,
    'numOfRows': num_of_row
}

    response = requests.get(url, params = params)

    results = response.json()

    print(results)

country_credit_rating(1, 100)

{'response': {'header': {'resultCode': 0, 'resultMsg': 'NORMAL SERVICE.'}, 'body': {'items': {'item': [{'ctryCd': 'GH', 'ctryNm': '가나', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GA', 'ctryNm': '가봉', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GY', 'ctryNm': '가이아나', 'evalGrd': '5', 'evalDd': '20251017'}, {'ctryCd': 'GM', 'ctryNm': '감비아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GP', 'ctryNm': '과달루프', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GT', 'ctryNm': '과테말라', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'GU', 'ctryNm': '괌', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GD', 'ctryNm': '그레나다', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'GR', 'ctryNm': '그리스', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'GL', 'ctryNm': '그린랜드', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'GN', 'ctryNm': '기니', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'GW', 'ctryNm': '기니비사우', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'NA', 'ctryNm': '나미비아', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'UM', 'ctryNm': '나바사섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NR', 'ctryNm': '나우루', 'evalGrd': '3', 'evalDd': '20241121'}, {'ctryCd': 'NG', 'ctryNm': '나이지리아', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': 'SS', 'ctryNm': '남수단', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'ZA', 'ctryNm': '남아프리카공화국', 'evalGrd': '4', 'evalDd': '20250703'}, {'ctryCd': 'GS', 'ctryNm': '남조지아.남샌드위치군도', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NL', 'ctryNm': '네덜란드', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'NP', 'ctryNm': '네팔', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'NO', 'ctryNm': '노르웨이', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': None, 'ctryNm': '노르웨이속령', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NF', 'ctryNm': '노포크 아일랜드', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'NZ', 'ctryNm': '뉴질랜드', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'NC', 'ctryNm': '뉴칼레도니아', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'NU', 'ctryNm': '니우에', 'evalGrd': '5', 'evalDd': '20251230'}, {'ctryCd': 'NE', 'ctryNm': '니제르', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'NI', 'ctryNm': '니카라과', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'TW', 'ctryNm': '대만', 'evalGrd': '2', 'evalDd': '20250703'}, {'ctryCd': 'KR', 'ctryNm': '대한민국', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'DK', 'ctryNm': '덴마크', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'DM', 'ctryNm': '도미니카 연방', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'DO', 'ctryNm': '도미니카공화국', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'DE', 'ctryNm': '독일', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'TL', 'ctryNm': '동티모르', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'LA', 'ctryNm': '라오스', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'LR', 'ctryNm': '라이베리아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'LV', 'ctryNm': '라트비아', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'RU', 'ctryNm': '러시아', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LB', 'ctryNm': '레바논', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LS', 'ctryNm': '레소토', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'RE', 'ctryNm': '레위니옹', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': None, 'ctryNm': '로스속령', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'RO', 'ctryNm': '루마니아', 'evalGrd': '3', 'evalDd': '20260206'}, {'ctryCd': 'LU', 'ctryNm': '룩셈부르크', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'RW', 'ctryNm': '르완다', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'LY', 'ctryNm': '리비아', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'LT', 'ctryNm': '리투아니아', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'LI', 'ctryNm': '리히텐슈타인', 'evalGrd': '1', 'evalDd': '20241121'}, {'ctryCd': 'MG', 'ctryNm': '마다가스카르', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MH', 'ctryNm': '마샬군도', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': 'YT', 'ctryNm': '마요뜨', 'evalGrd': '5', 'evalDd': '20251230'}, {'ctryCd': 'MO', 'ctryNm': '마카오', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'MW', 'ctryNm': '말라위', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MY', 'ctryNm': '말레이시아', 'evalGrd': '2', 'evalDd': '20250703'}, {'ctryCd': 'ML', 'ctryNm': '말리', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'MQ', 'ctryNm': '말티니크', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'IM', 'ctryNm': '맨섬', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'MX', 'ctryNm': '멕시코', 'evalGrd': '3', 'evalDd': '20251017'}, {'ctryCd': 'ES', 'ctryNm': '멜리야', 'evalGrd': '4', 'evalDd': '20251230'}, {'ctryCd': 'MC', 'ctryNm': '모나코', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'MA', 'ctryNm': '모로코', 'evalGrd': '3', 'evalDd': '20260206'}, {'ctryCd': 'MU', 'ctryNm': '모리셔스', 'evalGrd': '3', 'evalDd': '20250703'}, {'ctryCd': 'MR', 'ctryNm': '모리타니아', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': 'MZ', 'ctryNm': '모잠비크', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'ME', 'ctryNm': '몬테네그로', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'MS', 'ctryNm': '몬트세라트', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'MD', 'ctryNm': '몰도바', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'MV', 'ctryNm': '몰디브', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'MT', 'ctryNm': '몰타', 'evalGrd': '2', 'evalDd': '20231006'}, {'ctryCd': 'MN', 'ctryNm': '몽골', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'US', 'ctryNm': '미국', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'VI', 'ctryNm': '미국령 버진군도', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'AS', 'ctryNm': '미국령 사모아', 'evalGrd': '5', 'evalDd': '20241121'}, {'ctryCd': None, 'ctryNm': '미드웨이섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'MM', 'ctryNm': '미얀마', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'FM', 'ctryNm': '미크로네시아', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'VU', 'ctryNm': '바누아투', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'BH', 'ctryNm': '바레인', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'BB', 'ctryNm': '바베이도스', 'evalGrd': '6', 'evalDd': '20241121'}, {'ctryCd': 'VA', 'ctryNm': '바티칸', 'evalGrd': '2', 'evalDd': '20241121'}, {'ctryCd': 'BS', 'ctryNm': '바하마', 'evalGrd': '4', 'evalDd': '20251017'}, {'ctryCd': 'BD', 'ctryNm': '방글라데시', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'BM', 'ctryNm': '버뮤다', 'evalGrd': '2', 'evalDd': '20251230'}, {'ctryCd': 'VE', 'ctryNm': '베네수엘라', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BJ', 'ctryNm': '베넹', 'evalGrd': '6', 'evalDd': '20251017'}, {'ctryCd': None, 'ctryNm': '베이커홀랜드섬', 'evalGrd': '7', 'evalDd': '20251230'}, {'ctryCd': 'VN', 'ctryNm': '베트남', 'evalGrd': '4', 'evalDd': '20250703'}, {'ctryCd': 'BE', 'ctryNm': '벨기에', 'evalGrd': '1', 'evalDd': '20251230'}, {'ctryCd': 'BY', 'ctryNm': '벨라루스', 'evalGrd': '7', 'evalDd': '20260206'}, {'ctryCd': 'BZ', 'ctryNm': '벨리즈', 'evalGrd': '7', 'evalDd': '20231006'}, {'ctryCd': 'BA', 'ctryNm': '보스니아-헤르체코비나', 'evalGrd': '6', 'evalDd': '20260206'}, {'ctryCd': 'BW', 'ctryNm': '보츠와나', 'evalGrd': '3', 'evalDd': '20250703'}, {'ctryCd': 'BO', 'ctryNm': '볼리비아', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BI', 'ctryNm': '부룬디', 'evalGrd': '7', 'evalDd': '20250703'}, {'ctryCd': 'BF', 'ctryNm': '부르키나파소', 'evalGrd': '7', 'evalDd': '20251017'}, {'ctryCd': 'BT', 'ctryNm': '부탄', 'evalGrd': '6', 'evalDd': '20250703'}, {'ctryCd': 'MP', 'ctryNm': '북마리아나 군도', 'evalGrd': '3', 'evalDd': '20251230'}, {'ctryCd': 'MK', 'ctryNm': '북마케도니아', 'evalGrd': '5', 'evalDd': '20260206'}]}, 'pageNo': 1, 'totalCount': 259, 'numOfRows': 100}}}

In [ ]:
# data.go.kr
## 국토교통부 아파트 매매 실거래가 자료
import requests 
import xml.etree.ElementTree as ET

SERVICE_KEY = ''
url = "https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade"

def fetch_apt_trade(serviceKey, LAWD_CD, DEAL_YMD):
    params = {
        "serviceKey" : serviceKey,
        "LAWD_CD" : LAWD_CD,
        "DEAL_YMD" : DEAL_YMD
    }

    response = requests.get(url, params = params)
    print(response.content)

fetch_apt_trade(SERVICE_KEY, LAWD_CD = '11110', DEAL_YMD = '202604')